### PR TITLE
Ability to merge entries by hiera

### PR DESCRIPTION
**Pull request by TuningYourCode**

### CODE REVIEW

**Comment by chrekh** [comment]
Thanks,

Yes, possibility to merge hiera data for hosts::entries is a good idea.  In fact I don't think it's neccesary to have a parameter to enable that. It can do it all the time.  Do you think skipping $merge_entries and just use $entries as default for hiera_has would work?

 $entries_output = hiera_hash('hosts::entries', $entries)
 
Also, I prefer to update version in metadata.json my self. when doing a new release.

**Comment by TuningYourCode** [comment]
should work, i will do a short test.

**Comment by chrekh** [comment]
Looks good. If your tests also proves good and you squash the commits to a single commit (for cleaner history) I'll merge it.

**Comment by TuningYourCode** [comment]
Works for me as intended :)

**Pull request merged**
